# Generated by Django 4.1.7 on 2023-04-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_personnel_projet_service_delete_internship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
    ]
