# Generated by Django 4.1.7 on 2023-04-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_delete_blogs_service_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='description',
            new_name='descriptionn',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='libelle',
            new_name='libellee',
        ),
    ]
