# Generated by Django 4.1.7 on 2023-05-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_description_projet_descriptionn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='progression',
            field=models.FloatField(default=0),
        ),
    ]
