# Generated by Django 4.1.7 on 2023-05-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projet_progression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='progression',
        ),
    ]
