# Generated by Django 4.1.7 on 2023-05-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_projet_progression'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='progression',
            field=models.FloatField(default=0.0),
        ),
    ]
