# Generated by Django 4.1.7 on 2023-05-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_projet_progression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='progression',
            field=models.IntegerField(default=0),
        ),
    ]
