# Generated by Django 4.1.7 on 2023-05-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_projet_progression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='contact',
            name='emailv',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projet',
            name='progression',
            field=models.IntegerField(),
        ),
    ]
