# Generated by Django 4.1.7 on 2023-05-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_remove_contact_phonenumber_contact_emailv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('projet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.projet')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='equipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='personnels', to='portfolio.equipe'),
        ),
    ]
